sudo: required


services:
  - docker

before_install:
  - docker build -t ninux/mdl:latest .

script:
  - docker run -v $PWD:/mdl ninux/mdl echo Ok from MDL
  - docker run -v $PWD:/mdl ninux/mdl
  - docker run --rm -i lukasmartinelli/hadolint < Dockerfile
